profile_links:
  description: "Add quick links on user pages so users can find easily the important preference pages or settings."
  type: objects
  default: 
    [
      { "icon": circle-user, "label": Profile Picture, "page": account, "setting": user-avatar },
      { "icon": user-pen, "label": About me, "page": profile, "setting": user-bio },
      { "icon": image, "label": Profile Header, "page": profile, "setting": user-profile-bg },
      { "icon": address-card, "label": User Card Background, "page": profile, "setting": user-card-bg },
      { "icon": location-dot, "label": Location, "page": profile, "setting": user-location },
      { "icon": globe, "label": Web Site, "page": profile, "setting": user-website },
    ]
  schema:
    name: "link"
    identifier: label
    properties:
      icon:
        type: string
        required: true
      label:
        type: string
        required: true
      page:
        type: enum
        choices:
          - account
          - security
          - profile
          - emails
          - notifications
          - tracking
          - users
          - interface
          - navigation-menu
          - chat
      setting:
        type: string
profile_menu_preference_items:
  description: >
    Add items to the custom profile menu tab so users can more easily navigate to preference pages or settings.
    Each item can optionally include a "label" field to override the default translated text based on the "page" value.
  type: objects
  default: 
    [
      { "icon": user, "page": account },
      { "icon": user-pen, "page": profile },
      { "icon": lock, "page": security },
      { "icon": bell, "page": notifications },
      { "icon": desktop, "page": interface },
    ]
  schema:
    name: "item"
    identifier: page
    properties:
      icon:
        type: string
      label:
        type: string
      page:
        type: enum
        choices:
          - account
          - security
          - profile
          - emails
          - notifications
          - tracking
          - users
          - interface
          - navigation-menu
          - chat
      setting:
        type: string
profile_menu_extra_items:
  description: "Add items to the custom profile menu tab which appears before the Log Out button."
  type: objects
  default: 
    []
  schema:
    name: "item"
    identifier: label
    properties:
      icon:
        type: string
      label:
        type: string
        required: true
      url:
        type: string
        required: true
        validations:
          url: true
button_icon:
  default: "pencil"
  type: string
  description: "Change the quick profile link menu button icon on user pages"
enabled_user_profile_dropdown:
  default: true
  type: bool
  description: "Enable user profile dropdown on user page"
  refresh: true
enabled_user_menu_tab:
  default: true
  type: bool
  description: "Enable custom profile user menu tab"
  refresh: true
user_menu_tab_icon:
  default: "user"
  type: string
  description: "Change the custom profile user menu tab icon"
svg_icons:
  default: "circle-user|address-card"
  type: list
  list_type: "compact"
  description: "List of FontAwesome 6 icons used in this theme component"
